name: Code Test Workflow
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code 
        uses: actions/checkout@v4

      - name: Maven Test
        run: mvn test

      - name: Maven checkstyle
        run: mvn checkstyle:checkstyle
      
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7
        # Run sonar-scanner
      - name: SonarQube Scan
        run: sonar-scanner
            -Dsonar.host.url=https://sonarcloud.io/
            -Dsonar.login=2b92979bc08388966fa6529749d0bd1c7f758331
            -Dsonar.organization=silver-action
            -Dsonar.projectKey=silver-action
            -Dsonar.sources=$GITHUB_WORKSPACE
            -Dsonar.sources=src/ 
            -Dsonar.junit.reportsPath-target/surefire-reports/ 
            -Dsonar.jacoco.reportsPath-target/jacoco.exec 
            -Dsonar.java.checkstyle.reportPaths-target/checkstyle-result.xml 
            -Dsonar.java.binaries-target/test-classes/com/visualpathit/account
